# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df9a67098e344e070f54eec5f497f8b436b0c21c7d8bac900d88b94117b5303a22d398942cddf316982f2b81a226f6252ddf302fc9e3f8d45b59ceb9f863307b

test:
  secret_key_base: c8a9c86c555ab8fbb5edb262176b59ae628be68e02356d808e635d9774714c34ba5f357c1500280cdcfc45cfd14ca576b712074e10e4595ef560a94e44fd7a5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
